### ISSUE TITLE
Prometheus shared instance is not thread-safe

### ISSUE THREAD

**Issue by t089** [MrLotU/SwiftPrometheus#1]
Hey, consider me an early adaptor as I am running a fork of VaporMonitoring 1.0 currently in production to monitor a microservice. One [change I had to do](https://github.com/t089/VaporMonitoring/commit/19b3738086c6f7e5bb9b2225a35233da520779c1) in my fork was to isolate the shared state of collected metrics behind a lock (serial queue). Otherwise you might run into subtle undefined behavior. Xcode will warn you about this, if you enable the thread sanitizer runtime diagnostic.

In this project the same problem exists. The `shared` prometheus instance will be accessed from different `EventLoop`s (threads) at the same time reading and mutating the `metrics` storage. This needs to be synchronized by some form of locking.

You can see this by running your example and:

`wrk -t 1 -c 100 -d 5m "http://localhost:8080/hello"`

and then accessing the prometheus endpoint. Xcode (with thread sanitizer enabled) will show you a race-condition warning.

**Comment by MrLotU** [comment]
Hi,

First off, thanks for reaching out and adopting 😄, greatly appreciated! I see what you're saying and will try to get this fixed! To be honest though, I have no idea how all these thread things work, and how/where to fix this issue 😅. I'll do some research, but if you have any pointers for me, that'd be greatly appreciated!

**Comment by t089** [comment]
Hey, no worries. This stuff can be quite an [art](https://www.researchgate.net/publication/213876653_The_Art_of_Multiprocessor_Programming) of its own. I’m happy to help you. Let me come back to you with a concrete example how to solve the threading issue.

**Comment by MrLotU** [comment]
Thread safety should have been achieved with the 0.2.0 release and the [Vapor Monitoring 2.1.1 release](https://github.com/vapor-community/VaporMonitoring/releases/tag/2.1.1)
