### ISSUE TITLE
Trying to tag from 0.0.0-alpha.1 gets you 0.3.0

### ISSUE THREAD

**Issue by Yasumoto** [MrLotU/SwiftPrometheus#14]
### Steps to reproduce

Specify this in your `Package.swift`

```swift
.package(url: "https://github.com/MrLotU/SwiftPrometheus.git", from: "0.0.0-alpha.1")
```

and you'll pull in version `0.3.0`.

I know mucking with published git tags isn't ideal, but maybe we should delete the old `0.3.0` releases and rename them to something that won't collide with the NIO1-supported tags? 🤔 

### Expected behavior

We get "mainline" `0.0.0` versions.

**Comment by MrLotU** [comment]
Ah, dang. I thought the SPM versioning system would cover us there. Another option would be to publish a `1.x` for NIO 1 and go directly to `2.x` for NIO 2. Happy to hear anyone's thoughts.

**Comment by weissi** [comment]
@MrLotU / @Yasumoto but `from: 0.0.0-alpha.1` means `0.0.0-alpha.1 ..< 1.0.0` so that you would get a `0.3.0` (if released) is correct, right?

**Comment by MrLotU** [comment]
Yeah, this is the problem right now. I already had a `0.3.0` released previously. But right now users should get `0.0.0-alpha.1` not `0.3.0` since it's newer.

**Comment by weissi** [comment]
@MrLotU why not `1.0.0-alpha.1` then?

**Comment by weissi** [comment]
or `0.4.0-alpha.1`

**Comment by MrLotU** [comment]
We have that too, for the NIO 2 supported version :)

**Comment by weissi** [comment]
:)

**Comment by MrLotU** [comment]
`0.4.0-alpha.1` would work. But I think `0.3.0` -> `0.4.0-alpha.1` will have some breaking changes

**Comment by weissi** [comment]
> But I think `0.3.0` -> `0.4.0-alpha.1` will have some breaking changes

As per SemVer that's okay for `0.x` stuff, also already you have `0.0.0-alpha.1 --> 0.3.0` with breaking changes, right?

**Comment by MrLotU** [comment]
Ah, yeah. I think that's the easiest way to resolve this for now then. I'll publish `0.4.0-alpha.1` :)

**Comment by Yasumoto** [comment]
Best of all worlds, thanks friends!

**Comment by MrLotU** [comment]
`0.4.0-alpha.1` released. @Yasumoto could you please check if updating to `from: "0.4.0-alpha.1` works and if so, close this issue? 😄

**Comment by Yasumoto** [comment]
Yep! Updated https://github.com/vapor-community/VaporMonitoring/pull/5 and working a-ok 👌 🎉
