### ISSUE TITLE
Configurable label separator char replacements

### ISSUE THREAD

**Issue by ktoso** [MrLotU/SwiftPrometheus#29]
### Feature Request

Offer some configuration to replace characters in labels, i.e. when people in their libraries have `Counter("things.specificThing.thingsToCound")` that's an invalid label for prometheus. So we should allow some `labelSubstitutions = [".": "_"]` or perhaps some other way?

#### Motivation Behind Feature

Libraries which offer metrics via Swift Metrics generally "should not know" details about formats of labels that any specific backends require. This is mostly about the use of `.` (prom crashes on those, other backends like those) as separator vs using `_` (prom likes those, other backends dislike those).

#### Alternatives or Workarounds

- No go alternative: force all possible libraries to avoid `.` 😉

**Comment by Mordil** [comment]
As part of this, I would also expect SwiftPrometheus to handle uppercase labels being provided, by forcing all labels to be lowercased - for the same reason that Konrad provided regarding `.` vs `_`

**Comment by Mordil** [comment]
This is also now causing sharp edges with libraries that provide metrics through the SwiftMetrics interface: https://gitlab.com/Mordil/RediStack/-/issues/76

**Comment by MrLotU** [comment]
I will create something for this in SwiftPrometheus, but I think in the future this would be helpful in swift-metrics itself. A set of `LabelSanitizers` as you will. Of course SwiftPrometheus could provide some defaults, but I wouldn't be surprised if other libraries run into similar issues
