### ISSUE TITLE
Implement swift-metrics

### ISSUE THREAD

**Issue by Yasumoto** [MrLotU/SwiftPrometheus#3]
### Feature Request

We should implement the workflow laid out by [`swift-metrics`](https://github.com/apple/swift-metrics) which will allow this to be plugged in as one of the backends services can choose to utilize.

#### Motivation Behind Feature

Support the SSWG standardization.

#### Feature Description

This will require a bump in major version since it will drastically change the API.

**Comment by ktoso** [comment]
Can we mark in which milestone this feature was released?
