### ISSUE TITLE
Add import of UIKit to use the library on an iOS client

### ISSUE THREAD

**Issue by matiasvillaverde** [MrLotU/SwiftPrometheus#33]
I tried to use the library from an iOS app, and everything is compatible except that the compiler gets a bit confused of where to use`CGFloat`. 

While trying to compile we get this error
` Use of undeclared type 'CGFloat' `

This gets fixed by adding a compiler flag to know if we need to import `CoreGraphics` on iOS.

### Steps to reproduce

1. Import Prometheus library to an iOS App
2. Try to compile the app
3. Error will prevent compiling

### Expected behavior

Just be able to compile on iOS 

* OS version: iOS 12
* Swift version: 5.1
* Serverside Swift Framework: -
* Framework version: 1.0.0-alpha

**Comment by MrLotU** [comment]
Fixed per #34

**Comment by MrLotU** [comment]
Now available in https://github.com/MrLotU/SwiftPrometheus/releases/tag/1.0.0-alpha.7
