### ISSUE TITLE
Testing metrics endpoint

### ISSUE THREAD

**Issue by mcmikius** [MrLotU/SwiftPrometheus#40]
Hi, @MrLotU ! I read the your discussion. But I still did't understand how to set up SwiftPrometneus to work with tests. In my case it is required to check that metrics are returned along the route.
I initialize the application:
`override func setUpWithError() throws { app = Application(.testing) try configure(app) }`
Next, I call the route and at least wait for an answer - Ok. But the server error comes.
`func testAppMetrics() throws { try app.test(.GET, "v1/metrics", afterResponse: { (res) in XCTAssertEqual(res.status, .ok) let contentType = try XCTUnwrap(res.headers.contentType) XCTAssertEqual(contentType, .plainText) XCTAssertNotNil(res.content) XCTAssertNotNil(res.body) }) }`
I use
`@testable import App @testable import Metrics import XCTVapor`
And in main.swift - `MetricsSystem.bootstrap(PrometheusClient())`
I would be grateful if you could explain why .internalServerError returns? But when I call the same route through the API client everything works.

**Comment by MrLotU** [comment]
If an internalServerError is returned, there should be more logging indicating what exactly is causing the error. However, this is something in your vapor application and not within SwiftPrometheus.

**Comment by mcmikius** [comment]
@MrLotU Thank You
