### ISSUE TITLE
Gauge.record() implementation likely not right

### ISSUE THREAD

**Issue by ktoso** [MrLotU/SwiftPrometheus#7]
The piece of code implementing the metrics `Gauge.record()`  by making them an `add` operation is likely not good: https://github.com/MrLotU/SwiftPrometheus/blob/master/Sources/PrometheusMetrics/PrometheusMetrics.swift#L24-L44

I say likely, since the API does not really well define it and we need to fix it over there as well: https://github.com/apple/swift-metrics/issues/34 `Gauge.record() is under-defined`

Let's see what outcome there is and then make sure we implement the right style here -- i.e. it may have to become a "set".

**Comment by MrLotU** [comment]
Just saw the comment by @tomerd on the issue you linked. I’ll update it!

**Comment by MrLotU** [comment]
Fixed in https://github.com/MrLotU/SwiftPrometheus/commit/31d6964f7240125b07235a1f75e2601dbea74680

**Comment by ktoso** [comment]
Looks good, via PR would be nicer so there's a "paper trail" that it resolved this issue and not just an "update" :)
